name: Build docs

on:
  push:
    branches:
      - main
      - mike-test
      - pub-2023

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # HOTFIX for https://github.com/actions/runner/issues/2033
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

      # - name: Build docs
      #   uses: ./
      #   with:
      #     args: mkdocs build

      # Deployment is done via mike, this would delete versions deployed by mike
      # - name: Deploy docs to gh-pages branch
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site

      - name: Build and deploy docs with mike
        uses: ./
        with:
          args: sh -c "git config --global  user.name github-actions[bot];git config --global user.email "github-actions[bot]@users.noreply.github.com";mike deploy --push 2023"